Testsuite: AlunoTests
Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0,22 sec
------------- Standard Output ---------------
--Output from testInsercao--
------------- ---------------- ---------------
------------- Standard Error -----------------
--Output from testInsercao--
2013-07-06 08:12:26,345 [main] ERROR util.JDBCExceptionReporter  - Table "ALUNO" not found; SQL statement:
select this_.id as id8_0_, this_.version as version8_0_, this_.account_expired as account3_8_0_, this_.account_locked as account4_8_0_, this_.ativo as ativo8_0_, this_.email as email8_0_, this_.matricula as matricula8_0_, this_.nome as nome8_0_, this_.password_expired as password9_8_0_, this_."password" as password10_8_0_ from aluno this_ where this_.matricula=? [42102-164]

------------- ---------------- ---------------

Testcase: testInsercao took 0,207 sec
	Caused an ERROR
could not execute query; SQL [select this_.id as id8_0_, this_.version as version8_0_, this_.account_expired as account3_8_0_, this_.account_locked as account4_8_0_, this_.ativo as ativo8_0_, this_.email as email8_0_, this_.matricula as matricula8_0_, this_.nome as nome8_0_, this_.password_expired as password9_8_0_, this_."password" as password10_8_0_ from aluno this_ where this_.matricula=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query
org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute query; SQL [select this_.id as id8_0_, this_.version as version8_0_, this_.account_expired as account3_8_0_, this_.account_locked as account4_8_0_, this_.ativo as ativo8_0_, this_.email as email8_0_, this_.matricula as matricula8_0_, this_.nome as nome8_0_, this_.password_expired as password9_8_0_, this_."password" as password10_8_0_ from aluno this_ where this_.matricula=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query
	at AlunoTests.testInsercao(AlunoTests.groovy:26)
Caused by: org.hibernate.exception.SQLGrammarException: could not execute query
Caused by: org.h2.jdbc.JdbcSQLException: Table "ALUNO" not found; SQL statement:
select this_.id as id8_0_, this_.version as version8_0_, this_.account_expired as account3_8_0_, this_.account_locked as account4_8_0_, this_.ativo as ativo8_0_, this_.email as email8_0_, this_.matricula as matricula8_0_, this_.nome as nome8_0_, this_.password_expired as password9_8_0_, this_."password" as password10_8_0_ from aluno this_ where this_.matricula=? [42102-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.Parser.readTableOrView(Parser.java:4753)
	at org.h2.command.Parser.readTableFilter(Parser.java:1080)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1686)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1793)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1680)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1523)
	at org.h2.command.Parser.parseSelect(Parser.java:1511)
	at org.h2.command.Parser.parsePrepared(Parser.java:405)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1121)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)

